Dev/utils
IvanOsokin/Just_Something pull request #8
Opened 2021-12-17 14:55 UTC by IvanOsokin

1. Поправил:
   - std::shared_ptr на ptr::weak_ptr у поля _bulletManager в Character (в TestScene не стал менять std::shared_ptr на ptr::weak_ptr, так как наша сцена является и владельцем объекта класса BulletManager, и его создателем);
   - захват в лямбде в BulletManager::SceneBorderCollision();
   - конструкцию if на std::optional<T>::value_or в некоторых методах в BulletManager;
   - разыменование итератора на operator[] в BulletFactory.
2. Вынес использлвание математических функций в отдельную область Utils.
3. Заменил действующий код с учетом новых функций.

2021-12-17 16:31 UTC, KOMMYHAP approved these changes

2021-12-17 16:47 UTC, KOMMYHAP requested changes

2021-12-17 16:47 UTC, KOMMYHAP commented on projects/libalienland/include/CMakeLists.txt
> +	Utils.H
У тебя тут "H" заглавная)

2021-12-17 16:47 UTC, KOMMYHAP commented on projects/libalienland/include/Utils.h
> +const float pi = 3.141593f;
Я предлагаю унести эту константу тоже в скоуп Utils.

2021-12-17 16:47 UTC, KOMMYHAP commented on projects/libalienland/src/Utils.cpp
> +static const float s_fromRadToDeg = 180.0f / pi;
Для общеобразовательных целей.
Посмотри про "безымянный namespace". Если кратко, то это способ уйти от static для определения локальных в рамках единицы трансляции (грубо "в рамках .cpp файла") переменных/функций/классов.
То есть твой код равносилен следующему:
```
namespace
{
    const float s_fromRadToDeg = 180.0f / pi;
}
```

Я лично предпочитаю именно их, а не писать static.

2021-12-17 16:47 UTC, KOMMYHAP commented on projects/libalienland/src/Utils.cpp
> +		;
Что-то у тебя поехала верстка)

2021-12-17 16:47 UTC, KOMMYHAP commented on projects/libalienland/src/Utils.cpp
> +		return std::powf((std::powf(vector.x, 2.0f) + std::powf(vector.y, 2.0f)), 0.5f);
Ты не задавал себе вопрос, что быстрее sqrt(x) или powf(x, 0.5)?

2021-12-20 15:55 UTC, IvanOsokin commented on projects/libalienland/src/Utils.cpp
> +static const float s_fromRadToDeg = 180.0f / pi;
Не знал про anonymous namespace. Удобная вещь еще в том плане, что можно большой объем кода заключить в него, не объявляя кучу статиков.

Нашел еще такую инфу
![Screenshot_2](https://user-images.githubusercontent.com/85408016/146782440-7edbd152-f5d0-4478-aef0-33ae68adf2bf.jpg)

2021-12-20 16:01 UTC, IvanOsokin commented on projects/libalienland/src/Utils.cpp
> +		return std::powf((std::powf(vector.x, 2.0f) + std::powf(vector.y, 2.0f)), 0.5f);
После твоего вопроса я задал его себе) Поискал в инете и измерил сам: и sqrt, и AxA (особенно квадрат числа) в разы быстрее, чем std::pow. А вариант AxA даже на порядок.

Твой вопрос касаля корня квадратного. Но я также переделал и возведение в квадрат.

![Screenshot_3](https://user-images.githubusercontent.com/85408016/146796142-db31b740-babe-4678-b914-f2a1fceb588c.jpg)

2021-12-21 13:06 UTC, merged