Dev/utils
IvanOsokin/Just_Something pull request #9
Opened 2021-12-21 15:32 UTC by IvanOsokin

Создал файл для преобразований типов в библиотеке SFML и реализовал необходимые функции по переводу одних типов в другие. Причесал код с использованием новых функций.

2021-12-21 15:47 UTC, KOMMYHAP commented
Давай попробуем в стиле стандартного каста `static_cast`: `Utils::VectorCast<T>(...)`. 
То есть сделать реализацию шаблонной, которая внутри кастует поля вектора к типу `T`.
Глядя на твой утиль видимо нам потребуется две реализации: от вектора (`Vec2`) и от координат (`x, y`).

2021-12-21 15:48 UTC, KOMMYHAP requested changes

2021-12-21 15:48 UTC, KOMMYHAP commented on projects/libalienland/include/SfmlUtils.h
> +	sf::Vector2f ToVector2f(int x, int y);
Об этом речь

2021-12-22 17:08 UTC, KOMMYHAP commented
В первой функции давай явно укажем, что на вход требуется вектор, а не какой-то тип T.

Также хотелось бы свести одну функцию в другую, как я показывал тебе на примере конструкторов в твоём классе String.

2021-12-23 14:34 UTC, KOMMYHAP requested changes

2021-12-23 14:34 UTC, KOMMYHAP commented on projects/libalienland/include/SfmlUtils.h
> +		return VectorCast<T>(vector.x, vector.y);
Но ведь ты всего лишь переименовал тип T в тип Vector :)
Изначально моей целью было избавиться от возможности передать в VectorCast(const T &) что-либо кроме sf::Vector, т.к. сейчас ты туда можешь передать абсолютно любой тип.
Фактически, конечно, сейчас ты туда можешь передать только тип, у которого есть поля x и y, но я настаиваю, чтобы тип sf::Vector был указан явно в сигнатуре твоей функции.

2021-12-23 14:49 UTC, IvanOsokin commented on projects/libalienland/include/SfmlUtils.h
> +		return VectorCast<T>(vector.x, vector.y);
Я просто тебя неправильно понял)

2021-12-23 14:56 UTC, IvanOsokin commented on projects/libalienland/include/SfmlUtils.h
> +		return VectorCast<T>(vector.x, vector.y);
Готово.

2021-12-23 15:00 UTC, merged